sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t carlos/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true carlos/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-437308597054"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"